// Code generated by go-resemble. DO NOT EDIT.

//lint:file-ignore U1000 This file is automatically generated; ignore unused code checks

package plumbing

import "fmt"
import "io/ioutil"

const assetsEmbedded bool = false

func getAsset(name string) ([]byte, error) {
	var rvp string
	if len(name) > 0 {
		rvp = "/home/thijs/code/github.com/thijzert/doc-hoarder/web/assets/" + name
	} else {
		return nil, fmt.Errorf("asset not found")
	}

	return ioutil.ReadFile(rvp)
}
